kind: Service
apiVersion: v1
metadata:
  name: mainframe-service # Service name
spec:
  type: LoadBalancer
  selector:
    app: mainframe-service # Label selector. The Service targets Pods that use this label
  ports:
  - port: 8080 # Port of the service (internally)

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mainframe-service
  labels:
    app: mainframe-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainframe-service
  template:
    metadata:
      labels:
        app: mainframe-service
    spec:
      containers:
      - image: ckurze/mainframe-service
        name: mainframe-service
        env:
          - name: TZ
            value: CET
          - name: spring.datasource.url
            value: jdbc:oracle:thin:@oracledb-service:1521:XE
          - name: spring.datasource.username
            value: CARINSURANCE
          - name: spring.datasource.password
            value: carinsurance