apiVersion: v1
kind: Pod
metadata:
    name: mainframe-service
    labels:
      env: mainframe-service
spec:
  containers:
  - image: ckurze/mainframe-service
    name: mainframe-service
    env:
      - name: TZ
        value: CET
      - name: spring.datasource.url
        value: jdbc:oracle:thin:@10.23.251.48:1521:XE
      - name: spring.datasource.username
        value: CARINSURANCE
      - name: spring.datasource.password
        value: carinsurance
