apiVersion: v1
kind: Service
metadata:
  name: insurance-portal-service
spec:
  selector:
    app: insurance-portal
  ports:
  - protocol: TCP
    nodePort: 30101
    targetPort: 3000
  type: NodePort