apiVersion: v1
kind: Pod
metadata:
    name: oracledb
    labels:
      env: oracledb
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - image: felixreichenbach/oracledb:11.2.0.2-xe
    name: oracledb
#    resources:
#      limits:
#        memory: 1024Mi
#      requests:
#        memory: 1024Mi
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    env:
      - name: ORACLE_PWD
        value: "qwer1234"