kind: Service
apiVersion: v1
metadata:
  name: oracledb-service # Service name
spec:
  type: LoadBalancer
  selector:
    env: oracledb # Label selector. The Service targets Pods that use this label
  ports:
  - port: 1521 # Port used to access the Service from within the cluster.
    targetPort: 1521 # Port opened by targeted Pods

---
apiVersion: v1
kind: Pod
metadata:
    name: oracledb
    labels:
      env: oracledb
spec:
  volumes:
  - name: dshm
    emptyDir:
      medium: Memory
  containers:
  - image: felixreichenbach/oracledb:11.2.0.2-xe
    name: oracledb
#    resources:
#      limits:
#        memory: 1024Mi
#      requests:
#        memory: 1024Mi
    volumeMounts:
      - mountPath: /dev/shm
        name: dshm
    env:
      - name: ORACLE_PWD
        valueFrom:
          secretKeyRef:
            name: oracle-pass
            key: password
