apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: dataloader
  labels:
    app: dataloader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataloader
  template:
    metadata:
      labels:
        app: dataloader
    spec:
      containers:
      - image: python:alpine3.7
        name: dataloader