apiVersion: v1
kind: Service
metadata:
  name: mainframe-portal-service
spec:
  selector:
    app: mainframe-portal
  ports:
  - protocol: TCP
    nodePort: 30100
    targetPort: 3000
  type: NodePort